import type { Metadata } from 'next'
import { Inter, Lexend, Lora, Nunito } from 'next/font/google'
import './globals.css'

const lora = Lora({ variable: '--lora-font', subsets: ['latin'] })
const nunito = Nunito({ variable: '--nunito-font', subsets: ['latin'] })
const inter = Inter({ variable: '--inter-font', subsets: ['latin'] })
const lexend = Lexend({
    variable: '--lexend-font',
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={`${inter.variable} ${lexend.variable} ${nunito.variable} ${lora.variable}`}
            >
                <div className="font-inter text-[#232323]">{children}</div>
            </body>
        </html>
    )
}
